#!/bin/sh
set -e
# Automatically added by dh_gconf
if [ "$1" = remove ] || [ "$1" = upgrade ]; then
	gconf-schemas --unregister compiz-annotate.schemas compiz-blur.schemas compiz-clone.schemas compiz-core.schemas compiz-cube.schemas compiz-dbus.schemas compiz-decoration.schemas compiz-fade.schemas compiz-fs.schemas compiz-gconf.schemas compiz-glib.schemas compiz-ini.schemas compiz-inotify.schemas compiz-minimize.schemas compiz-move.schemas compiz-place.schemas compiz-plane.schemas compiz-png.schemas compiz-regex.schemas compiz-resize.schemas compiz-rotate.schemas compiz-scale.schemas compiz-screenshot.schemas compiz-svg.schemas compiz-switcher.schemas compiz-video.schemas compiz-water.schemas compiz-wobbly.schemas compiz-zoom.schemas gwd.schemas 
fi
# End automatically added section
