#!/bin/sh
set -e
# Automatically added by dh_gconf
if [ "$1" = "configure" ]; then
	gconf-schemas --register gnome-volume-control.schemas gnome-sound-recorder.schemas gnome-audio-profiles.schemas 
fi
# End automatically added section
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/hicolor
fi
# End automatically added section
