#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = remove ] || [ "$1" = upgrade ] && \
   which install-docs >/dev/null 2>&1; then
	install-docs -r java-policy
fi
# End automatically added section
# Automatically added by dh_installdocs
if [ "$1" = remove ] || [ "$1" = upgrade ] && \
   which install-docs >/dev/null 2>&1; then
	install-docs -r debian-java-faq
fi
# End automatically added section
