#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/libdevmapper1.02" ]; then
	update-rc.d libdevmapper1.02 start 25 S . >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d libdevmapper1.02 start || exit $?
	else
		/etc/init.d/libdevmapper1.02 start || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section
