#!/bin/sh -e

if [ "$1" = "configure" ]; then
    MAN=/usr/share/man/man1
    BIN=/usr/bin
    update-alternatives --install \
	$BIN/vncviewer       vncviewer       $BIN/jtightvncviewer 40 \
	--slave \
	$MAN/vncviewer.1.gz  vncviewer.1.gz  $MAN/jtightvncviewer.1.gz \
	--slave \
	$MAN/xvncviewer.1.gz xvncviewer.1.gz $MAN/jtightvncviewer.1.gz \
	--slave \
	$BIN/xvncviewer      xvncviewer      $BIN/jtightvncviewer
fi



exit 0
