#!/bin/sh -e

if [ "$1" = "configure" ]; then
	# Get xfce-mcs-manager to reinit
	kill -s USR1 `pidof xfce-mcs-manager` >/dev/null 2>&1|| true

fi

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section


exit 0
