#!/bin/sh

set -e

if [ "$1" = "configure" ] || [ "$1" = "triggered" ] ||
   [ "$1" = "abort-upgrade" ]; then
    touch /usr/lib/xulrunner-1.9/.autoreg
    rm -f /usr/lib/xulrunner-1.9/components/compreg.dat \
          /usr/lib/xulrunner-1.9/components/xpti.dat
    cd /usr/lib/xulrunner-1.9
    export HOME=`mktemp -d`
    ./run-mozilla.sh ./xpcshell -e "" ||
    rm -f /usr/lib/xulrunner-1.9/components/compreg.dat \
          /usr/lib/xulrunner-1.9/components/xpti.dat
    rm -rf "$HOME"
fi



